name: CI with CML

on: 
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          
      - name: Authenticate to Google Cloud
        run: |
          echo "$GCP_SERVICE_ACCOUNT_KEY" > gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-key.json
          gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}


      - name: Set up CML 
        uses: iterative/setup-cml@v2
        
      - name: Install dependencies and run unit tests
        run: |
          pip install -r "Week 2/requirements.txt"
          python -m unittest "Week 2/test.py" 2>&1 | tee test_output.txt
        
      - name: Create CML report
        env: 
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Unit Test Output" > report.md
          echo '```' >> report.md
          cat test_output.txt >> report.md
          echo '```' >> report.md
        
          cml comment create --publish report.md
      
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Print current directory and contents
        run: |
          pwd
          ls -R

      - name: Build Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/helical-canto-459816-r4/my-repo/iris-api:latest docker build -t <your-image-name> "Week 2/docker_demo"


      - name: Push Docker Image to Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/helical-canto-459816-r4/my-repo/iris-api:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials demo-gke-iris-cluster \
            --zone us-central1 \
            --project polar-pillar-461115-g2

      - name: Deploy latest image to GKE
        run: |
          kubectl set image deployment/demo-iris-workload iris-api-sha256-1=us-central1-docker.pkg.dev/polar-pillar-461115-g2/my-repo/iris-api:latest
