name: CI with CML

on: 
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: helical-canto-459816-r4
          install_components: 'gke-gcloud-auth-plugin'


      - name: Set up CML 
        uses: iterative/setup-cml@v2
        
      - name: Install dependencies and run unit tests
        run: |
          pip install -r "Week 2/requirements.txt"
          python -m unittest "Week 2/test.py" 2>&1 | tee test_output.txt
        
      - name: Create CML report
        env: 
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Unit Test Output" > report.md
          echo '```' >> report.md
          cat test_output.txt >> report.md
          echo '```' >> report.md
        
          cml comment create --publish report.md
      
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # - name: Print current directory and contents
      #   run: |
      #     pwd
      #     ls -R

      - name: Build Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/helical-canto-459816-r4/my-repo/iris-api:latest "Week 2/docker_demo"

      # - name: Install GKE auth plugin
      #   run: |
      #     gcloud components install gke-gcloud-auth-plugin --quiet


      - name: Push Docker Image to Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/helical-canto-459816-r4/my-repo/iris-api:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials demo-gke-iris-cluster \
            --zone us-central1 \
            --project helical-canto-459816-r4
      - name: Deploy latest image to GKE
        run: |
          kubectl set image deployment/demo-iris-workload iris-api-sha256-1=us-central1-docker.pkg.dev/helical-canto-459816-r4/my-repo/iris-api:latest
